server:
  port: 8023

spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


zuul:
  routes:
    api-v1:
      path: /api-v1/**
      serviceId: feign-server
    api-v2:
      path: /api-v2/**
      serviceId: ribbon-server