server:
  port: 8024

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
          username:
          password:


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka/
